#   _____             _          _____ _           _
#  / ____|           | |        / ____| |         | |
# | (___   __ _ _ __ | | _____ | |    | |__   __ _| |_
#  \___ \ / _` | '_ \| |/ / _ \| |    | '_ \ / _` | __|
#  ____) | (_| | | | |   < (_) | |____| | | | (_| | |_
# |_____/ \__,_|_| |_|_|\_\___/ \_____|_| |_|\__,_|\__|

# cache-clear-time is how often cache should be cleaned in minutes, default is 2. cache-clear-age is how old messages should be removed from cache (in minutes), default is 10
cache-clear-time: 2
cache-clear-age: 10