main: com.videosambo.sankochat.Main
version: 1.2.1
name: SankoChat
author: videosambo
description: Tool for clean chat

commands:
  sankochat:
    description: Reload config file of sankochat
    usage: /sankochat

permissions:
  sankochat.bypass.blockedwords:
    description: Allows you to skip check blocked words list
    default: op
  sankochat.bypass.cooldown:
    description: Allows you to bypass cooldown for chat
    default: op
  sankochat.bypass.repeat:
    description: Allows you to type same messaga again
    default: op
  sankochat.bypass.similar:
    description: Allows you to skip similiar message check
    default: op
  sankochat.bypass.filter:
    description: Allows you to send urls, ips and domain names
    default: op
  sankochat.bypass.caps:
    description: Allows you to bypass caps check
    default: op
  sankochat.bypass.replaceword:
    description: Allows you to bypass replace word
    default: op
  sankochat.command.reload:
    description: Admin command for reload command
    default: op
  sankochat.command.resetdata:
    description: Admin command for reseting warnings
    default: op
  sankocaht.command.notifications:
    description: Notification permission
    default: op
  sankochat.*:
    description: Admin permissions
    default: op
    children:
     sankochat.bypass.blockedwords: true
     sankochat.bypass.cooldown: true
     sankochat.bypass.repeat: true
     sankochat.bypass.similar: true
     sankochat.bypass.filter: true
     sankochat.bypass.caps: true
     sankocaht.bypass.replaceword: true
     sankochat.command.reload: true
     sankochat.command.resetdata: true
     sankochat.notifications: true